[package]
authors = ["Lyssieth <raxixor@rax.ee>"]
edition = "2021"
name = "sauce_bot"
version = "0.1.0"
publish = false

[profile.dev]
lto = false

[profile.release]
lto = true

[dependencies]
color-eyre = "0.6.1"
tracing = "0.1.31"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
sauce-api = { version = "0.9.3", default-features = false, features = [
    "iqdb",
    "saucenao",
    "rustls",
] }
serde = { version = "1.0.136", features = ["derive"] }
# serenity = "0.10.10"
smart-default = "0.6.0"
tokio = { version = "1.17.0", features = ["full"] }
toml = "0.5.8"
url = "2.2.2"
r8limit = "0.2.2"
twilight-gateway = "0.9.1"
twilight-http = "0.9.1"
twilight-model = "0.9.2"
twilight-embed-builder = "0.9.0"
futures = "0.3.21"
twilight-interactions = "0.9.0"
twilight-util = { version = "0.9.1", features = ["full"] }
async-trait = "0.1.52"
