[package]
authors = ["Lyssieth <raxixor@rax.ee>"]
edition = "2018"
name = "sauce_bot"
version = "0.1.0"

[profile.dev]
lto = false

[profile.release]
lto = true

[dependencies]
eyre = "0.6.5"
log = "0.4.14"
pretty_env_logger = "0.4.0"
sauce-api = { version = "0.8.0", default-features = false, features = ["iqdb", "saucenao", "rustls"] }
serde = { version = "1.0.127", features = ["derive"] }
serenity = "0.10.8"
smart-default = "0.6.0"
tokio = { version = "1.9.0", features = ["full"] }
toml = "0.5.8"
url = "2.2.2"
