[package]
authors = ["Lyssieth <raxixor@rax.ee>"]
edition = "2021"
name = "sauce_bot"
version = "0.1.0"
publish = false

[profile.dev]
lto = false

[profile.release]
lto = true

[dependencies]
color-eyre = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
sauce-api = { version = "0.9", default-features = false, features = [
    "iqdb",
    "saucenao",
    "rustls",
] }
serde = { version = "1.0", features = ["derive"] }
serenity = "0.10"
smart-default = "0.6"
tokio = { version = "1.12", features = ["full"] }
toml = "0.5"
url = "2.2"
