[package]
authors = ["Lyssieth <raxixor@rax.ee>"]
edition = "2021"
name = "sauce_bot"
version = "0.1.0"
publish = false

[profile.dev]
lto = false

[profile.release]
lto = true

[dependencies]
color-eyre = "0.6.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
sauce-api = { version = "1.0.0", default-features = false, features = [
    "iqdb",
    "saucenao",
    "rustls",
] }
serde = { version = "1.0.147", features = ["derive"] }
# serenity = "0.10.10"
smart-default = "0.6.0"
tokio = { version = "1.22.0", features = ["full"] }
toml = "0.5.9"
url = "2.3.1"
twilight-gateway = "0.14.0"
twilight-http = "0.14.0"
twilight-model = "0.14.0"
futures = "0.3.25"
twilight-interactions = "0.14.1"
twilight-util = { version = "0.14.0", features = ["full"] }
async-trait = "0.1.58"
num-traits = "0.2.15"
