[package]
authors = ["Lyssieth <raxixor@rax.ee>"]
edition = "2021"
name = "sauce_bot"
version = "0.1.0"
publish = false

[profile.dev]
lto = false

[profile.release]
lto = true

[dependencies]
color-eyre = "0.5.11"
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.4", features = ["env-filter"] }
sauce-api = { version = "0.9.2-alpha.2", default-features = false, features = [
    "iqdb",
    "saucenao",
    "rustls",
] }
serde = { version = "1.0.132", features = ["derive"] }
serenity = "0.10.9"
smart-default = "0.6.0"
tokio = { version = "1.15.0", features = ["full"] }
toml = "0.5.8"
url = "2.2.2"
